inherits = "poimandres"
"ui.background" = {}
"ui.gutter" = {}
"ui.linenr" = { bg = "" }
comment = { fg = "brightYellow", modifiers = ["italic"] }
"ui.selection" = { bg = "darkerGray.50" }
"ui.selection.primary" = { bg = "bluishGray" }
"ui.virtual.jump-label" = { bg = "bg", fg = "offWhite", modifiers = [
  "reversed",
  "bold",
] }
